tomlPROJECT_ID = "bustling-tuner-448708-m1"
LOCATION = "us"
PROCESSOR_ID = "82e981697ac87a7e"

[gcp_service_account]
type = "service_account"
project_id = "bustling-tuner-448708-m1"
private_key_id = "e6381fdd4403dd461808643c5a855f720e64a3d5"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDbQcddJe7C/D8I
68WROm3vCRkNoZQNiNR9Pvktnqj14i+Oj/y+2L0M94Vjq8LhYn/nUyIOXdWgdXgY
q0HXXME8quWLd+NeC67XRmlGFbH08stkPjJ0RoERMkNXi59g1GQy/3kEjRR3W1NG
QkBSzeija8daCiDYl5bk0Ryi9EwpSxooC4iVKEi5OFDSzcQ0gfd2uVSu7383ie7z
u8X9dqinX9pgt4Fmiw8mcuwPusqzCM5/3WJQA/4OIz66Np7DdHYcLzzDWrGWe48h
ysp77e3N3RZ4RJQhEu1TYC4BgPG2Fuvh8Qu3ghHaG8RV1o8ocADx1RyjkNzrM7xQ
zE1mkGaRAgMBAAECggEACR8i8qqd1MnWu4HHjeOu6CdqPelvdeKv6GgCyNWVdOlM
jjNKUgxFTTFNANkH+gV1icOpIozf0tWgQfJ6AkIvHd2EQDmkIWj+BKG+xnYnmaey
M4Ds6251dyguqgk6f7ZGVuLO/5P4+oA3pjAiae98ErRsrj/GnwwrcGiMtvDP7FXK
Ualw8mP1v/efNyf1V9O8CdwWUynBJNsYDX8ztpyKgqjPkYtUTdS9wHx+ofxmKWT
jk0oHplVR7PFct6tkMXJol/PnA+1TXELUMRrlin/gxsJn3/w4l+t5YF3GxzwOczP
Nb5y0ShoNTE7L/8p2D6VaD0Ya9RVodldwwlk3FWA6wKBgQDubdHyJKpY5x1meWHR
9zIeBo4PTQxY0lmq5P2K9Mkw4EtyDe/GjrAWR9TGNiqWyp9P3bEL63RMLYaSc5Kp
WIYQPSDHfysk15X1J/jchjJGjh3qUEwa45EeAlXhVaxQkd8eafggmmgLTdFzXfpE
jXZrL2IwyuGYY3/4RXin7TzY3wKBgQDrakK/ycz7pUBhSlddg0vIZmpp+na4bMCh
nBC2zNf/+JR/hfWilPFxTbOymRzjzvNnpB//eHibwx/r7B2Od+b9NknY2iaAeoKR
HuLACcVy2MnCzevDDsoJCyZQ754LsB2a/vnaA97KooB1AHc67xAm72xteR/NaMO3
nMy7PFr+jwKBgFj5EkdR91+FnysGUMKRhFpAB/MdxWW/2UY0fYjFH+7lREIjgT6P
MJaf536v5+StaBXdnJveGV/z/SvZhPk814pnxTus8OSmrob1i6B/U3OQxQkTPdMq
6JRSOsoDtnG6fZBT6wv/kqPlPivW/fVm9LG61OFwVA8R0kdLZWME3JfxAoGBAMmE
OIc8E4AGQUoG/SpLTf/Jy6XUhPPyBCNTGOuiBfRTsapH3bDClrtKrFxhvN01Nh6t
28YwNe3/5b9qaxKdiNmQMz6x3utz83iOW8PPmXlqIavj4cEjU8bSCIaX105h/7XC
NdZuIbSLzjJZp7aHFeh+Yu6DFLocyAzQ6GAOlkX5AoGANBeAr7r5sfHjyKtjRCNA
h3ZfPkqq2+oah3TQeRB6gejbTsh95nboBn5w9nuf0ZV175BzYXF9RIHdjjx4KGSC
Ija9BX+qExD4UJGd7qj/OjMTm8rHfgf/830Kdzg1D0s+zzrlDQqOFewnlMtp9COY
uggPAsrKm0Ary3plHeWCd7o=
-----END PRIVATE KEY-----
"""
client_email = "essay-review@bustling-tuner-448708-m1.iam.gserviceaccount.com"
client_id = "102026510188251601181"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/essay-review%40bustling-tuner-448708-m1.iam.gserviceaccount.com"
